apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: moniejoint-ns
spec:
  type: NodePort
  selector:
    app: eureka-server
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      nodePort: 30002  # Static port for browser access
