apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: moniejoint-ns
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: us-central1-docker.pkg.dev/trusty-fuze-456211-j9/config-server:placeholder
          ports:
            - containerPort: 8001
          resources:
            limits:
              memory: "200Mi"
              cpu: "50m"
            requests:
              memory: "100Mi"
              cpu: "10m"
